title: "phgsouto's ramblings"
url: "https:/phgsouto.github.io"
baseurl: ""
timezone: America/Sao_Paulo
description: "phgsouto's ramblings about thechnology"

email: phgsouto@gmail.com
author: phgsouto <Pedro H. G. Souto>
avatar: "http://www.gravatar.com/avatar/fcf3a646d97e7dde7abcc34ffeb99b44"
profile: Nerd. Technology enthusiast.
twitter_username: phgsouto
github_username:  phgsouto
profile_links:
GitHub: "https://github.com/phgsouto"

header_pages:
  - index.md
  - about.md

footer: 'follow me on <a href="https://twitter.com/phgsouto">twitter</a>'

permalink: /archivers/:title

plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji

markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console
style: dark 
